Реализован функционал по ТЗ 15 спринта
Grigoriy-Popov/shareit pull request #3
Opened 2022-09-04 10:19 UTC by Grigoriy-Popov

2022-09-05 11:02 UTC, SnikerZi requested changes
Отличная работа, осталось совсем немного.

2022-09-05 11:02 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/requests/ItemRequestController.java
> +    @GetMapping("all")
GET /requests/all?from={from}&size={size} тут должен быть запрос такого формата

2022-09-05 11:02 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/user/User.java
>  @Getter
Рекомендую получше изучить Lombok, имеются аннотации, дублирующие функционал

2022-09-05 11:42 UTC, Grigoriy-Popov commented on src/main/java/ru/practicum/shareit/requests/ItemRequestController.java
> +    @GetMapping("all")
не совсем понял замечания, у меня вроде такой запрос и предусмотрен. Два RequestParam - from и size

2022-09-06 09:06 UTC, SnikerZi approved these changes
Спасибо за правки, теперь у тебя почти идеальная работа. Ты молодец.

2022-09-06 09:51 UTC, merged